package com.osaic.sample.util;

import com.osaic.sample.dto.AddressDto;
import com.osaic.sample.sql.model.Address;

public class AddressMapper {
	/**
	 * Converts an AddressDTO object to an Address entity object.
	 *
	 * @param dto The AddressDTO object to convert.
	 * @return The converted Address entity object.
	 */
	public static Address toEntity(AddressDto dto) {
		if (dto == null) {
			return null;
		}

		Address entity = new Address();
		// ID is often generated by the persistence layer for new entities,
		// so it might not be set during DTO to entity conversion for creation.
		// If updating an existing entity, you would set it.
		// entity.setId(dto.getId());

		entity.setCustomerId(dto.getCustomerId());
		entity.setAddress1(dto.getAddress1());
		entity.setAddress2(dto.getAddress2());
		entity.setCity(dto.getCity());
		entity.setState(dto.getState());
		entity.setCountry(dto.getCountry());

		// If createdAt is managed by the database (e.g., @CreationTimestamp),
		// you might not set it here for new entities.
		// For existing entities, you might copy it if the DTO provides it.
		// For this example, we assume it's set on creation and not directly from DTO.
		// entity.setCreatedAt(dto.getCreatedAt()); // Uncomment if DTO provides and you
		// want to copy

		return entity;
	}

	/**
	 * Converts an Address entity object to an AddressDTO object.
	 *
	 * @param entity The Address entity object to convert.
	 * @return The converted AddressDTO object.
	 */
	public static AddressDto toDto(Address entity) {
		if (entity == null) {
			return null;
		}

		AddressDto dto = new AddressDto();
		dto.setId(entity.getId());

		dto.setAddress1(entity.getAddress1());
		dto.setAddress2(entity.getAddress2());
		dto.setCity(entity.getCity());
		dto.setState(entity.getState());
		dto.setCountry(entity.getCountry());
		dto.setCustomerId(entity.getCustomerId());
		// dto.setCreatedAt(entity.getCreatedAt());

		return dto;
	}
}
